# Generated by Django 4.1.7 on 2023-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
