# Generated by Django 4.1.7 on 2023-04-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='title',
        ),
    ]
