# Generated by Django 4.1.7 on 2023-04-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_cars_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='rudder_location',
            field=models.CharField(default=1, max_length=100, verbose_name='Расположение руля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
